### ISSUE TITLE
active admin gem configuration

### ISSUE THREAD

**Issue by AaganMaskey** [AaganMaskey/FINAL_PROJECT#5]
There's an error while using active admin gem @capyl . Try installing the same gem.

**Comment by AaganMaskey** [comment]
No result after performing this command:
rails generate active_admin:install

**Comment by AaganMaskey** [comment]
@gkunwar & @capyl , No active admin files were created.

**Comment by gkunwar** [comment]
@AaganMaskey Is there any error ?

**Comment by AaganMaskey** [comment]
@gkunwar, I think rake db:migrate isn't working.

**Comment by gkunwar** [comment]
@AaganMaskey Can you please send the screehsoot of error terminal.

**Comment by AaganMaskey** [comment]
![screenshot from 2016-09-15 22-06-12](https://cloud.githubusercontent.com/assets/20100892/18557942/b0a3cc9a-7b90-11e6-992b-89a03dfd5640.png)

**Comment by AaganMaskey** [comment]
![screenshot from 2016-09-15 22-09-10](https://cloud.githubusercontent.com/assets/20100892/18558049/3b0bc04a-7b91-11e6-990e-87974ed3576c.png)

**Comment by gkunwar** [comment]
@AaganMaskey Add and install devise gem before you install active admin. 
https://github.com/plataformatec/devise

**Comment by AaganMaskey** [comment]
@gkunwar , admin gem configured but couldn't login with default username and password.

**Comment by gkunwar** [comment]
@AaganMaskey Did you run 'rake db:seed' command.

**Comment by AaganMaskey** [comment]
@gkunwar , everything seems to be messed up now ! When can we meet you sir? @capyl

**Comment by AaganMaskey** [comment]
active admin configured!
